<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>QoLiTea</AssemblyName>
    <Product>QoLiTea</Product>
    <Version>1.0.3</Version>
    <BepInExPluginGuid>rotn.dimethyltea.QoLiTea</BepInExPluginGuid>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>QoLiTea</RootNamespace>
    <GameManaged Condition="'$(GameManaged)' == ''">A:\SteamLibrary\steamapps\common\RiftOfTheNecroDancerOSTVolume1\RiftOfTheNecroDancer_Data\Managed</GameManaged>
    <GamePlugins Condition="'$(GamePlugins)' == ''">A:\SteamLibrary\steamapps\common\RiftOfTheNecroDancerOSTVolume1\BepInEx\plugins</GamePlugins>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.43" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ROTN">
      <HintPath>lib/RiftReadable.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>$(GameManaged)\Unity.Mathematics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManaged)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GameManaged)\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameManaged)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TicToc.ObjectPooling.Runtime">
      <HintPath>$(GameManaged)\TicToc.ObjectPooling.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameManaged)\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>$(GameManaged)\com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(GameManaged)\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>$(GameManaged)\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RiftOfTheNecroManager">
      <HintPath>$(GamePlugins)\RiftOfTheNecroManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QoLiTea.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="QoLiTea.Tests/**" />
    <None Remove="QoLiTea.Tests/**" />
  </ItemGroup>

</Project>
